# Full metric catalog — two categories (standard + external)

STANDARD_METRICS = {
    # ── DORA core ───────────────────────────────────────────────────────────
    "CFR": {
        "name":             "Change Failure Rate",
        "periodic_group":   "C4",
        "tier":             "devops",
        "unit":             "%",
        "source":           "source_control",
        "formula":          "Hotfix releases (patch-bumps within 24h of prior release) / total releases. Falls back to revert PRs / merged PRs for repos that do not use release tags.",
        "why":              "Measures how often releases ship broken and need an immediate patch — a core DORA quality metric.",
        "space_dimension":  "Performance",
    },
    "DF": {
        "name":             "Deployment Frequency",
        "periodic_group":   "C2",
        "tier":             "devops",
        "unit":             "deployments",
        "source":           "source_control",
        "formula":          "Count of releases (tags matching the configured pattern, default 'v*') in the period. Falls back to merged PRs to main for repos that do not tag releases.",
        "why":              "Tracks production release cadence — higher frequency correlates with lower risk per change and faster feedback loops.",
        "space_dimension":  "Performance",
    },
    "MTTR": {
        "name":             "Mean Time to Recover",
        "periodic_group":   "C5",
        "tier":             "devops",
        "unit":             "hours",
        "source":           "itsm",
        "formula":          "Avg hours from incident open to resolved",
        "why":              "Measures operational resilience — how quickly the team recovers from incidents.",
        "space_dimension":  "Performance",
    },
    "LTfC": {
        "name":             "Lead Time for Changes",
        "periodic_group":   "C2",
        "tier":             "devops",
        "unit":             "hours",
        "source":           "source_control",
        "formula":          "Mean time (hours) from code committed to code running in production. Reported only when production releases can be identified (release tags); otherwise not measurable.",
        "why":              "One of the four DORA key metrics. Measures end-to-end delivery latency: the time between a change being committed and that change reaching production users.",
        "space_dimension":  "Efficiency",
    },
    # ── Source control ───────────────────────────────────────────────────────
    "PRCT": {
        "name":             "PR Cycle Time",
        "periodic_group":   "F2",
        "tier":             "devops",
        "unit":             "hours",
        "source":           "source_control",
        "formula":          "Avg hours from MR open to merged",
        "why":              "Time spent in the code review phase — long cycles block developer throughput.",
        "space_dimension":  "Efficiency",
    },
    "PRSi": {
        "name":             "Pull Request Size",
        "periodic_group":   "F2",
        "tier":             "devops",
        "unit":             "lines",
        "source":           "source_control",
        "formula":          "Mean lines changed (additions + deletions) per merged pull request in the period.",
        "why":              "Larger PRs are harder to review and have lower defect-detection rates (Cohen, 2006). Tracks whether teams keep changes small enough for effective review.",
        "space_dimension":  "Efficiency",
    },
    "TWiP": {
        "name":             "Team Work in Progress",
        "periodic_group":   "F2",
        "tier":             "sustainability",
        "unit":             "count",
        "source":           "project_tracking",
        "formula":          "Count of in-progress issues at snapshot time",
        "why":              "High WiP causes context switching and delivery delays — a flow efficiency constraint.",
        "space_dimension":  "Efficiency",
    },
    # ── Sustainability ────────────────────────────────────────────────────────
    "BUR": {
        "name":             "Burnout Rate",
        "periodic_group":   "A",
        "tier":             "sustainability",
        "unit":             "%",
        "source":           "source_control",
        "formula":          "% of team with >3 commits outside 09:00–17:00 Mon–Fri CET/CEST",
        "why":              "Identifies the fraction of the team working unsustainable hours — individual sustainability risk.",
        "space_dimension":  "Satisfaction",
    },
    "AHCR": {
        "name":             "After-Hours Commit Rate",
        "periodic_group":   "A",
        "tier":             "sustainability",
        "unit":             "%",
        "source":           "source_control",
        "formula":          "After-hours commits / total commits × 100 (outside 09:00–17:00 Mon–Fri CET/CEST, weekends always count)",
        "why":              "Measures what share of overall commit activity happens outside working hours — a team-level signal of overload or unhealthy delivery pressure.",
        "space_dimension":  "Satisfaction",
    },
    "CQI": {
        "name":             "Code Quality Index",
        "periodic_group":   "C7",
        "tier":             "devops",
        "unit":             "%",
        "source":           "cicd",
        "formula":          "Pipeline success rate as proxy",
        "why":              "Overall pipeline health as a code quality proxy — sustained failures indicate systemic issues.",
        "space_dimension":  "Performance",
    },
    "MIC": {
        "name":             "Maintainability Issue Count",
        "periodic_group":   "C7",
        "tier":             "sustainability",
        "unit":             "count",
        "source":           "itsm",
        "formula":          "Open bugs older than 14 days",
        "why":              "Accumulated technical debt in issue form — older unresolved bugs signal prioritization problems.",
        "space_dimension":  "Performance",
    },
    "BF": {
        "name":             "Bus Factor",
        "periodic_group":   "E",
        "tier":             "sustainability",
        "unit":             "%",
        "source":           "source_control",
        "formula":          "% commits by top contributor",
        "why":              "Concentration risk — if one person leaves, critical knowledge walks out the door.",
        "space_dimension":  "Performance",
    },
    "BLDS": {
        "name":             "Build Count",
        "periodic_group":   "D1",
        "tier":             "devops",
        "unit":             "count",
        "source":           "cicd",
        "formula":          "Count of pipeline executions in period",
        "why":              "Raw build volume — useful for capacity and cost planning.",
        "space_dimension":  "Activity",
    },
    "PR": {
        "name":             "Pull Request Count",
        "periodic_group":   "F2",
        "tier":             "devops",
        "unit":             "count",
        "source":           "source_control",
        "formula":          "Count of MRs by state",
        "why":              "Pull request volume — tracks review load and code activity.",
        "space_dimension":  "Activity",
    },
    # ── Promoted from AI-derivable ───────────────────────────────────────────
    "CoDi": {
        "name":             "Code Diffusion",
        "periodic_group":   "F1",
        "tier":             "devops",
        "unit":             "%",
        "source":           "source_control",
        "formula":          "unique_files_changed / total_commits in period",
        "why":              "Measures how broadly changes spread across the codebase — high diffusion may indicate risky or poorly scoped changes.",
        "space_dimension":  "Performance",
    },
    "ChCo": {
        "name":             "Change Coupling",
        "periodic_group":   "C7",
        "tier":             "devops",
        "unit":             "count",
        "source":           "source_control",
        "formula":          "count of file pairs that change together above threshold frequency",
        "why":              "Reveals hidden dependencies between files not expressed in the architecture — high coupling increases change risk.",
        "space_dimension":  "Performance",
    },
    "PRRD": {
        "name":             "Pull Request Rework Duration",
        "periodic_group":   "F2",
        "tier":             "devops",
        "unit":             "hours",
        "source":           "source_control",
        "formula":          "sum(age_days * open_MR_weight) / total_open_MRs",
        "why":              "Captures time lost to rework in the review process — persistently high values indicate review quality or scope issues.",
        "space_dimension":  "Efficiency",
    },
    "WIQ": {
        "name":             "Work Item Quality",
        "periodic_group":   "F2",
        "tier":             "devops",
        "unit":             "%",
        "source":           "project_tracking",
        "formula":          "reopened_issues / total_resolved_issues in period",
        "why":              "Proxy for issue specification quality — high reopening rate indicates unclear requirements or incomplete resolution.",
        "space_dimension":  "Performance",
    },
    "EAc": {
        "name":             "Estimation Accuracy",
        "periodic_group":   "D4",
        "tier":             "devops",
        "unit":             "%",
        "source":           "project_tracking",
        "formula":          "1 - abs(estimated_points - actual_points) / estimated_points",
        "why":              "Measures planning reliability — consistent under- or over-estimation signals a process improvement opportunity.",
        "space_dimension":  "Performance",
    },
    "DIF": {
        "name":             "Documentation Improvement Frequency",
        "periodic_group":   "F1",
        "tier":             "devops",
        "unit":             "count",
        "source":           "source_control",
        "formula":          "commits with docs/ path changes / total commits",
        "why":              "Tracks whether documentation is maintained alongside code — low frequency is a technical sustainability risk.",
        "space_dimension":  "Efficiency",
    },
    "CIRT": {
        "name":             "CI Response Time",
        "periodic_group":   "F5",
        "tier":             "devops",
        "unit":             "minutes",
        "source":           "cicd",
        "formula":          "avg(pipeline_start_timestamp - commit_timestamp) in minutes",
        "why":              "Time from commit to first CI feedback — long waits fragment developer focus and reduce flow.",
        "space_dimension":  "Efficiency",
    },
    "IChps": {
        "name":             "Incident Handoffs to Target Team",
        "periodic_group":   "F3",
        "tier":             "devops",
        "unit":             "count",
        "source":           "itsm",
        "formula":          "sum(assignee_changes per incident) / total_incidents",
        "why":              "High handoff counts indicate unclear ownership or misrouted incidents — both increase resolution time.",
        "space_dimension":  "Performance",
    },
    "WIV": {
        "name":             "Work Item Volume",
        "periodic_group":   "D2",
        "tier":             "devops",
        "unit":             "count",
        "source":           "project_tracking",
        "formula":          "count of issues by type per sprint",
        "why":              "Tracks workload composition over time — useful for detecting scope creep or unplanned work accumulation.",
        "space_dimension":  "Activity",
    },
    "DPLY": {
        "name":             "Deployments",
        "periodic_group":   "D1",
        "tier":             "devops",
        "unit":             "count",
        "source":           "cicd",
        "formula":          "count of all pipeline runs with status success in period",
        "why":              "Raw deployment count distinct from Deployment Frequency — useful for volume-based capacity analysis.",
        "space_dimension":  "Activity",
    },
}

EXTERNAL_DATA_METRICS = {
    # Requires survey or HR system — cannot be computed from GitLab/Jira
    "DSAT": {"name": "Developer Satisfaction", "tier": "sustainability", "source": "survey",    "reason": "Requires periodic developer survey instrument"},
    "HAP":  {"name": "Developer Happiness",    "tier": "sustainability", "source": "survey",    "reason": "Requires periodic survey or mood tracking tool"},
    "PsyS": {"name": "Psychological Safety",   "tier": "sustainability", "source": "survey",    "reason": "Requires validated survey instrument (Google re:Work)"},
    "CogL": {"name": "Cognitive Load",         "tier": "sustainability", "source": "survey",    "reason": "Requires survey — no reliable behavioural proxy exists"},
    "RR":   {"name": "Retention Rate",         "tier": "sustainability", "source": "hr_system", "reason": "Requires HR information system access"},
    "AR":   {"name": "Attrition Rate",         "tier": "sustainability", "source": "hr_system", "reason": "Requires HR information system access"},
    "DT":   {"name": "Developer Tenure",       "tier": "sustainability", "source": "hr_system", "reason": "Requires HR information system access"},
    "ILR":  {"name": "Illness Rate",           "tier": "sustainability", "source": "hr_system", "reason": "Requires HR sick leave records"},
    "CSAT": {"name": "Customer Satisfaction",  "tier": "business",      "source": "crm",       "reason": "Requires CRM or NPS survey tool"},
    "TCO":  {"name": "Total Cost of Ownership","tier": "business",      "source": "finance",   "reason": "Requires finance system or AWS billing access"},
}

# Keep a reference alias for any code that still imports AI_DERIVABLE_METRICS
# (will be an empty dict — metrics have been promoted into STANDARD_METRICS)
AI_DERIVABLE_METRICS: dict = {}
